<?php
  session_start();
  require_once('./common/tokengen.php');
  generateToken();
  require_once('common/language.php');
  require_once(classLanguage::stringSetHtmlTop());
  require_once('./view/mid.php');
  require_once('./view/bottom.php');
?>
